### ISSUE TITLE
Not working for me - Lolin ESP12E

### ISSUE THREAD

**Issue by mantielero** [gavinlyonsrepo/NOKIA5110_TEXT#6]
I am using platformio. I am using LoLin ESP12E (nodemcuv2).

My `platformio.ini`:
```ini
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = NOKIA5110_TEXT
```

I have tried the two first examples and none of them worked. The only modification that I did was selecting the appropriate pins in my case:
```
// RST / CE / DC / DIN / CLK / VCC /LIGHT / GND
#define RST 0
#define CE 1
#define DC 2
#define DIN 3
#define CLK 4
```

I have managed to make it work with the following library: https://github.com/baghayi/Nokia_5110

So I don't know if there is something that can be made to enable your library with my board.

I am a newbie with this by the way.

**Comment by gavinlyonsrepo** [comment]
Hi 

I don't know much about  platformio,
I have tested it on ESP8266 NodeMCU ESP-12e module.
In the extras folder there is a file with pinouts used 
https://github.com/gavinlyonsrepo/NOKIA5110_TEXT/blob/master/extras/testedMCU_pinouts.txt

I suspect at this point your problem is a  pin naming/identification  issue. pins used for software SPI  are 
ESP8266 
`NOKIA5110_TEXT mylcd(D2, D1, D6, D7, D5);`

Note that in the boards the DX number is different to GPIO number 


[https://i.pinimg.com/736x/1a/04/f0/1a04f0d337a26fc94e1286ab142fee92.jpg](url)
 
Can you try these DX numbers in the code wired up as such and let me know results? 

regards

**Comment by gavinlyonsrepo** [comment]
Hi 

I have double checked with latest software 
I have a Lorin nodemcu v3 esp8266 esp-12e 
It works  here, again I don't use platformio just Arduino IDE.

In addition  to previous post with pin naming/identification possibility.
It also possible you could have a bias or contrast issue
Contrast can be adjusted in example file:  Try 0xB1 <-> 0xBF range
Bias can be adjusted in example file : Try 0x12 or 0x13 or 0x14

regards

**Comment by mantielero** [comment]
You are absolutely right. I missed the D before the numbers. I didn't know I had to do that. Now it works.

Thanks a lot.
